sudo: required
services:
  - docker

before_install:
  - docker build -t uokereh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run uokereh/react-test npm run build

after_success:
  -docker build -t uokereh/multi-client ./client
  -docker build -t uokereh/multi-nginx ./nginx
  -docker build -t uokereh/multi-server ./server
  -docker build -t uokereh/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push uokereh/multi-client
  - docker push uokereh/multi-nginx
  - docker push uokereh/multi-server
  - docker push uokereh/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-958923515642"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"