sudo: required
services:
  - docker

before_install:
  - docker build -t uokereh/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run uokereh/multi-docker npm run test -- --coverage

