sudo: required
services:
  - docker

before_install:
  - docker build -t uokereh/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run uokereh/multi-docker npm run build


  -docker build -t uokereh/client ./client
  -docker build -t uokereh/nginx ./nginx
  -docker build -t uokereh/server ./server
  -docker build -t uokereh/worker ./worker

