sudo: required
services:
  - docker

before_install:
  - docker build -t uokereh/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run uokereh/multi-docker npm test -- --coverage

after_success:
  -docker build -t uokereh/multi-client ./client
  -docker build -t uokereh/multi-nginx ./nginx
  -docker build -t uokereh/multi-server ./server
  -docker build -t uokereh/multi-worker ./worker

  - echo "$DOCK_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin